#pragma checksum "CursussenKopen.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "E470AB5909EEE8578BA149B421F20D706E49E5C306DE07F36786DEBCB89ED24A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Udemy;


namespace Udemy {
    
    
    /// <summary>
    /// CursussenKopen
    /// </summary>
    public partial class CursussenKopen : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 31 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblNaamStudent;
        
        #line default
        #line hidden
        
        
        #line 32 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCategorie;
        
        #line default
        #line hidden
        
        
        #line 33 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbCategorie;
        
        #line default
        #line hidden
        
        
        #line 34 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblOnderwerpen;
        
        #line default
        #line hidden
        
        
        #line 35 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnZoekCategorie;
        
        #line default
        #line hidden
        
        
        #line 36 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbOnderwerp;
        
        #line default
        #line hidden
        
        
        #line 37 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datagridAlleCursussen;
        
        #line default
        #line hidden
        
        
        #line 67 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtCursus;
        
        #line default
        #line hidden
        
        
        #line 68 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnZoekCursus;
        
        #line default
        #line hidden
        
        
        #line 69 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCursusKopen;
        
        #line default
        #line hidden
        
        
        #line 70 "CursussenKopen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTerugNaarOverzicht;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Udemy;component/cursussenkopen.xaml", System.UriKind.Relative);
            
            #line 1 "CursussenKopen.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 16 "CursussenKopen.xaml"
            ((Udemy.CursussenKopen)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.lblNaamStudent = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.lblCategorie = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.cmbCategorie = ((System.Windows.Controls.ComboBox)(target));
            
            #line 33 "CursussenKopen.xaml"
            this.cmbCategorie.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cmbCategorie_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.lblOnderwerpen = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.btnZoekCategorie = ((System.Windows.Controls.Button)(target));
            
            #line 35 "CursussenKopen.xaml"
            this.btnZoekCategorie.Click += new System.Windows.RoutedEventHandler(this.btnZoekCategorie_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.cmbOnderwerp = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.datagridAlleCursussen = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 9:
            this.txtCursus = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.btnZoekCursus = ((System.Windows.Controls.Button)(target));
            
            #line 68 "CursussenKopen.xaml"
            this.btnZoekCursus.Click += new System.Windows.RoutedEventHandler(this.btnZoeken_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btnCursusKopen = ((System.Windows.Controls.Button)(target));
            
            #line 69 "CursussenKopen.xaml"
            this.btnCursusKopen.Click += new System.Windows.RoutedEventHandler(this.btnCursusKopen_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btnTerugNaarOverzicht = ((System.Windows.Controls.Button)(target));
            
            #line 70 "CursussenKopen.xaml"
            this.btnTerugNaarOverzicht.Click += new System.Windows.RoutedEventHandler(this.btnTerugNaarOverzicht_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

