#pragma checksum "CursussenToevoegen.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "212971E3519184103633D3DF70DEC1B099A053A63824CD9E993687568E3D3B2E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Udemy;


namespace Udemy {
    
    
    /// <summary>
    /// CursussenToevoegen
    /// </summary>
    public partial class CursussenToevoegen : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 33 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblNaamCursus;
        
        #line default
        #line hidden
        
        
        #line 34 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTaal;
        
        #line default
        #line hidden
        
        
        #line 35 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblNiveau;
        
        #line default
        #line hidden
        
        
        #line 36 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCategorie;
        
        #line default
        #line hidden
        
        
        #line 37 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblOnderwerp;
        
        #line default
        #line hidden
        
        
        #line 38 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPrijs;
        
        #line default
        #line hidden
        
        
        #line 39 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblBeschrijving;
        
        #line default
        #line hidden
        
        
        #line 40 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGebruiker;
        
        #line default
        #line hidden
        
        
        #line 41 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNaamCursus;
        
        #line default
        #line hidden
        
        
        #line 46 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbOndertitels;
        
        #line default
        #line hidden
        
        
        #line 47 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbExamens;
        
        #line default
        #line hidden
        
        
        #line 48 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbCodeerOefeningen;
        
        #line default
        #line hidden
        
        
        #line 49 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbOefenExamens;
        
        #line default
        #line hidden
        
        
        #line 51 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbTaal;
        
        #line default
        #line hidden
        
        
        #line 53 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbNiveau;
        
        #line default
        #line hidden
        
        
        #line 55 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbCategorie;
        
        #line default
        #line hidden
        
        
        #line 57 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbOnderwerpen;
        
        #line default
        #line hidden
        
        
        #line 60 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPrijs;
        
        #line default
        #line hidden
        
        
        #line 63 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblDecimaal;
        
        #line default
        #line hidden
        
        
        #line 64 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPrijsDecimaal;
        
        #line default
        #line hidden
        
        
        #line 67 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbBeschrijving;
        
        #line default
        #line hidden
        
        
        #line 71 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTerugNaarOverzicht;
        
        #line default
        #line hidden
        
        
        #line 72 "CursussenToevoegen.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMaakCursusAan;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Udemy;component/cursussentoevoegen.xaml", System.UriKind.Relative);
            
            #line 1 "CursussenToevoegen.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 16 "CursussenToevoegen.xaml"
            ((Udemy.CursussenToevoegen)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.lblNaamCursus = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.lblTaal = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.lblNiveau = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblCategorie = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.lblOnderwerp = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.lblPrijs = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.lblBeschrijving = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.lblGebruiker = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.txtNaamCursus = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.cbOndertitels = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            this.cbExamens = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 13:
            this.cbCodeerOefeningen = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 14:
            this.cbOefenExamens = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 15:
            this.cmbTaal = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 16:
            this.cmbNiveau = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 17:
            this.cmbCategorie = ((System.Windows.Controls.ComboBox)(target));
            
            #line 56 "CursussenToevoegen.xaml"
            this.cmbCategorie.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cmbCategorie_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.cmbOnderwerpen = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 19:
            this.txtPrijs = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.lblDecimaal = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.txtPrijsDecimaal = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.txtbBeschrijving = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.btnTerugNaarOverzicht = ((System.Windows.Controls.Button)(target));
            
            #line 71 "CursussenToevoegen.xaml"
            this.btnTerugNaarOverzicht.Click += new System.Windows.RoutedEventHandler(this.btnTerugNaarOverzicht_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.btnMaakCursusAan = ((System.Windows.Controls.Button)(target));
            
            #line 72 "CursussenToevoegen.xaml"
            this.btnMaakCursusAan.Click += new System.Windows.RoutedEventHandler(this.btnMaakCursusAan_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

